#+TITLE: CHANGELOG
#+AUTHOR: Adolfo Villafiorita

* Version 1.0.1

- Documentation updated

* Version 1.0.0

- Dropped support for the Europass XML format. The version currently generated
  by resme (corresponding to the 3.3.0 version of the Europass schema) is no
  longer supported by the Europass website.  Information about the required
  changes to make to the format is difficult to retrieve.
- Bug fixes

* Version 0.5.1

  A bug-fixing release.

  More in details:

  - [bug] Add dependency to =classy_hash=
  - [doc] Fix links to source code and Changelog.
  - [doc] Merge Release History and Changelog.
  - [doc] Fix version numbers in headers of Changelog (1.5.0 -> 0.5.0)

* Version 0.5.0
  - [user] New command =view= allows to view the template used
    for generating a resume in a specific format
  - [user] Check command is now based on ClassyHash
  - [code] Various changes to the code

* Version 0.4.0

  Version 0.4.0 refactors all generation commands under =generate=, provides
  new filtering options, adds =-e= option (for custom templates), and
  refactors various portions of code.  It also revises this document
  and fixes some minor bugs.

  More in details:
  
  - [user] New option =--skip= allows to skip some top-level sections.
    You mileage might vary, as some formats might require the
    information you are trying to skip
  - [user] New command =generate= is now used to generate the Resume
    in different formats.
  - [user] New option =--erb= allows to specify a custom template for
    generating the resume. Use it in conjunction with =view= (released
    in version 1.5.0) to jump-start your layout.
  
* Version 0.3.2 and 0.3.1

  Version 0.3.2 and 0.3.1 fix errors with the Europass format: lists of
  projects, interests, ... are now properly formatted.

* Version 0.3

  Version 0.3 Introduces output to org-mode, introduces references for the CV,
  improves output to JSON, adds a =check= command, removes useless blank
  lines in the output, supports =-%>= in the ERB templates, fixes
  various typos in the documentation, introduces various new formatting
  functions, to simplify template generation

* Version 0.2

  Version 0.2 improves output of volunteering activities and other information
  in the Europass and *significantly improves error and warning
  reporting*

* Version 0.1

  Version 0.1 is the first release
