#+TITLE: RESME - A Resume Generator
#+AUTHOR: Adolfo Villafiorita
#+DATE: <2020-07-14 Tue>
#+STARTUP: showall

Keep your resume in YAML and output it Org Mode and JSON Resume.  Org Mode is
flexible enough to export to various other formats.

The rendering engine is based on ERB. This simplifies the creation of
new output formats (and extending/modifying the YML structure to one's
needs).

** Installation
   :PROPERTIES:
   :CUSTOM_ID: installation
   :END:

Add this line to your application's Gemfile:

#+begin_example ruby
  gem 'resme'
#+end_example

And then execute:

#+begin_example sh
  bundle
#+end_example

Or install it yourself as:

#+begin_example sh
  gem install resme
#+END_EXAMPLE

** Usage
   :PROPERTIES:
   :CUSTOM_ID: usage
   :END:

Start with:

#+begin_example sh
  resme init
#+end_example

which generates a YML template for your resume in the current directory.
Comments in the YML file should help you fill the various entries.
Notice that most entries are optional and you can remove sections which
are not relevant for your resume.

You can now generate a resume using one of the existing formats:

#+begin_example sh
  resme --format org --build resume.yml
#+end_example

If you are not satisfied with the provided templates, you can write your own
(see below).

Full syntax:

#+begin_src sh :results raw output :wrap example
resme --help
#+end_src

#+RESULTS:
#+begin_example
resme [options] - Format and manage a resume in YAML
        --format FORMAT              Output format
        --init                       Init a new resume
        --validate FILENAME          Validate the resume
        --build FILENAME             Build the resume in FILENAME
        --sections FILENAME          List sections in FILENAME
        --list                       List available templates
        --except x,y,z               Excluded section
        --cat TEMPLATE               View a template
        --version
    -h, --help                       Print this help
#+end_example

** Checking validity
   :PROPERTIES:
   :CUSTOM_ID: checking-validity
   :END:

Use the =--validate= option to verify whether your YAML file conforms with
the intended syntax.

#+begin_example sh
  resme --validate resume.yaml
#+end_example

** Dates in the resume
   :PROPERTIES:
   :CUSTOM_ID: dates-in-the-resume
   :END:

Enter dates in the resume in one of the following formats:

- Any format accepted by Ruby for a full date (year, month, day)
- YYYY-MM-DD
- YYYY-MM
- YYYY

The third and the forth format allows you to enter "partial" dates
(e.g., when the month or the day have been forgotten or are irrelevant).

** Development
   :PROPERTIES:
   :CUSTOM_ID: development
   :END:

After checking out the repo, run =bin/setup= to install dependencies.
You can also run =bin/console= for an interactive prompt that will allow
you to experiment.

To install this gem onto your local machine, run
=bundle exec rake install=. To release a new version, update the version
number in =version.rb=, and then run =bundle exec rake release=, which
will create a git tag for the version, push git commits and tags, and
push the =.gem= file to [[https://rubygems.org][rubygems.org]].

** Contributing
   :PROPERTIES:
   :CUSTOM_ID: contributing
   :END:

Bug reports and pull requests are welcome on GitHub at
https://github.com/avillafiorita/resme.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

The gem is available as open source under the terms of the [[http://opensource.org/licenses/MIT.txt][MIT License]].

** Change Log

In [[file:./CHANGELOG.org][CHANGELOG.org]]

** Bugs
   :PROPERTIES:
   :CUSTOM_ID: bugs
   :END:

An unknown number of unknown bugs.

